apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-1
  labels:
    app: wordpress
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - 10.76.35.132:6789
      - 10.76.35.129:6789
      - 10.76.35.133:6789
    pool: rbd
    image: wordpress-pv-1
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-2
  labels:
    app: wordpress
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - 10.76.35.132:6789
      - 10.76.35.129:6789
      - 10.76.35.133:6789
    pool: rbd
    image: wordpress-pv-2
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Delete
