#!/bin/sh

CEPH_FSID="10BA0602-8EF1-4F17-9B20-0D41345D60B2"

CEPH_MON_NODES=(node01 node02 node03)

CEPH_MON_INITIAL_MEMBERS=""
for CEPH_MON_NODE in ${CEPH_MON_NODES[@]}; do
    CEPH_MON_INITIAL_MEMBERS="$CEPH_MON_INITIAL_MEMBERS,${CEPH_MON_NODE}"
    CEPH_MON_NODE_IP=$(resolveip -s ${CEPH_MON_NODE})
    CEPH_MON_HOSTS="${CEPH_MON_HOSTS},${CEPH_MON_NODE_IP}"
done
CEPH_MON_INITIAL_MEMBERS=${CEPH_MON_INITIAL_MEMBERS:1}
CEPH_MON_HOSTS=${CEPH_MON_HOSTS:1}
