apiVersion: v1
kind: Pod
metadata:
  name: ceph-rbd-test
spec:
  containers:
  - name: cephrbd-rw
    image: busybox
    command:
    - sh
    - -c
    - while true; do sleep 1; done
    volumeMounts:
    - mountPath: "/mnt/cephrbd"
      name: cephrbd
  volumes:
  - name: cephrbd
    rbd:
      monitors:
      - 10.76.35.132:6789
      - 10.76.35.129:6789
      - 10.76.35.133:6789
      user: admin
      image: ceph-rbd-test
      pool: rbd
      secretRef:
        name: ceph-secret
